theme: jekyll-theme-minimal
title: CASCODE-LABS
description: Open Source Circuit Design
logo: /logo/vecteezy_isometric-microchip-on-a-white-background_.jpg
header_pages:
  - about.md
author:
  name: Curtis Mayberry
  email: "Curtisma3@gmail.com"
